//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABN_cashposition
    {
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string Currency { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<int> valid { get; set; }
        public string User { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public long FullId { get; set; }
        public string Description { get; set; }
    }
}
