//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABNReconResult
    {
        public System.DateTime ReportDate { get; set; }
        public Nullable<System.DateTime> TradeDate { get; set; }
        public string Symbol { get; set; }
        public string TYPE { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public string ABN_cp { get; set; }
        public string BOSymbol { get; set; }
        public string BOTradeNumber { get; set; }
        public string BOcp { get; set; }
        public Nullable<double> Mty { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<System.DateTime> BODate { get; set; }
        public string TypeOfTrade { get; set; }
        public string COMMENT { get; set; }
        public Nullable<double> ExchFee { get; set; }
        public string ExchFeeCcy { get; set; }
        public Nullable<double> ClearFee { get; set; }
        public string ClearingFeeCcy { get; set; }
        public long fullid { get; set; }
        public Nullable<double> BOfee { get; set; }
        public string BOCurrency { get; set; }
        public string BOAccount { get; set; }
    }
}
