//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADSSCashGroupped
    {
        public System.DateTime ReportDate { get; set; }
        public string Currency { get; set; }
        public Nullable<double> OpeningCash { get; set; }
        public Nullable<double> ClosingCash { get; set; }
        public Nullable<double> Trades { get; set; }
        public Nullable<double> SWAPs { get; set; }
        public Nullable<double> Deposit { get; set; }
        public long fullid { get; set; }
        public string comment { get; set; }
        public Nullable<double> Commission { get; set; }
        public string Cp { get; set; }
        public Nullable<double> OptionPremium { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<double> ExcessShortage { get; set; }
        public Nullable<double> NAV { get; set; }
        public Nullable<double> Interest { get; set; }
    }
}
