//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Axi_Trades
    {
        public Nullable<long> TradeNumber { get; set; }
        public string TradeCode { get; set; }
        public string Product { get; set; }
        public Nullable<System.DateTime> TradeDate { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public string CcyPair { get; set; }
        public string Direction { get; set; }
        public string Ccy1 { get; set; }
        public Nullable<double> Ccy1Amount { get; set; }
        public Nullable<double> TradeRate { get; set; }
        public Nullable<double> Ccy2Amount { get; set; }
        public string Account { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public long id { get; set; }
    }
}
