//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Axi_SettlingTrades
    {
        public Nullable<long> TradeNumber { get; set; }
        public string TradeCode { get; set; }
        public string Product { get; set; }
        public Nullable<System.DateTime> TradeDate { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public string ccyPair { get; set; }
        public string direction { get; set; }
        public string ccy1 { get; set; }
        public Nullable<double> cc1Amount { get; set; }
        public Nullable<double> TradeRate { get; set; }
        public Nullable<double> ccy2Amount { get; set; }
        public Nullable<double> ConsolidationRate { get; set; }
        public Nullable<double> RealizedPnL { get; set; }
        public string EUR { get; set; }
        public Nullable<System.DateTime> Reportdate { get; set; }
        public long id { get; set; }
        public string Account { get; set; }
    }
}
