//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnMapping
    {
        public long fullid { get; set; }
        public string Brocker { get; set; }
        public string Type { get; set; }
        public string FileType { get; set; }
        public Nullable<int> cReportDate { get; set; }
        public Nullable<int> cTradeDate { get; set; }
        public Nullable<int> cBrokerId { get; set; }
        public Nullable<int> cSymbol { get; set; }
        public Nullable<int> cType { get; set; }
        public Nullable<int> cQty { get; set; }
        public Nullable<int> cPrice { get; set; }
        public Nullable<int> cValuedate { get; set; }
        public Nullable<int> cExchangeFees { get; set; }
        public Nullable<int> cFee { get; set; }
        public Nullable<int> cValue { get; set; }
        public Nullable<int> cExchangeOrderId { get; set; }
        public Nullable<int> cTypeOfTrade { get; set; }
        public Nullable<int> cComment { get; set; }
        public Nullable<int> cExchFeeCcy { get; set; }
        public Nullable<int> cCcy { get; set; }
        public Nullable<int> cTradeTime { get; set; }
        public Nullable<int> cLineStart { get; set; }
        public string cTabName { get; set; }
        public Nullable<int> cQtySell { get; set; }
        public string DateFormat { get; set; }
        public string Replacesymbols { get; set; }
        public Nullable<int> cSide { get; set; }
        public string Delimeter { get; set; }
        public Nullable<int> Mty { get; set; }
        public string ValueDateFormat { get; set; }
        public Nullable<int> cClearingFee { get; set; }
        public Nullable<int> cClearingFeeCcy { get; set; }
        public Nullable<int> cStrike { get; set; }
        public Nullable<int> cOptionType { get; set; }
        public Nullable<int> cFee2 { get; set; }
        public Nullable<int> cFee3 { get; set; }
    }
}
