//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporateActions
    {
        public long id { get; set; }
        public string symbolId { get; set; }
        public string isin { get; set; }
        public Nullable<System.DateTime> DeclaredDate { get; set; }
        public Nullable<System.DateTime> ExDate { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.DateTime> PayableDate { get; set; }
        public Nullable<double> DividendAmount { get; set; }
        public string DividendFrqncy { get; set; }
        public string DividendType { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<double> BOQty { get; set; }
        public Nullable<System.DateTime> LastTradeDate { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string Comment { get; set; }
    }
}
