//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpCost
    {
        public Nullable<System.DateTime> Date { get; set; }
        public string account { get; set; }
        public string BOsymbol { get; set; }
        public string CPsymbol { get; set; }
        public string BOCp { get; set; }
        public string CP { get; set; }
        public Nullable<double> SumQty { get; set; }
        public Nullable<double> NumberOfTrades { get; set; }
        public Nullable<double> BOFee { get; set; }
        public Nullable<double> ExchFee { get; set; }
        public Nullable<double> CpFee { get; set; }
        public string CpExchCcy { get; set; }
        public string CpClearingCCY { get; set; }
        public string BOCcy { get; set; }
        public long fullid { get; set; }
    }
}
