//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpPosition
    {
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string Brocker { get; set; }
        public Nullable<System.DateTime> TradeDate { get; set; }
        public string Symbol { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Price { get; set; }
        public string BOSymbol { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<int> cp_id { get; set; }
        public string Type { get; set; }
        public string OptionType { get; set; }
        public Nullable<double> Strike { get; set; }
        public Nullable<double> Value { get; set; }
        public string ccy { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<int> valid { get; set; }
        public string username { get; set; }
        public long id { get; set; }
    }
}
