//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBBORecon_mapping
    {
        public long fullid { get; set; }
        public string boaccountid { get; set; }
        public string dbcp { get; set; }
        public string accountNameCP { get; set; }
        public Nullable<int> valid { get; set; }
        public System.DateTime timestamp { get; set; }
        public string user { get; set; }
        public string NameProcess { get; set; }
    }
}
