//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emir
    {
        public string Pre_novation_UTI { get; set; }
        public string Common_Data_Delegated { get; set; }
        public string Reporting_Firm_ID { get; set; }
        public string Other_Counterparty_ID { get; set; }
        public string Other_Counterparty_ID_Type { get; set; }
        public string Reporting_Firm_Corporate_Name { get; set; }
        public string Reporting_Firm_Registered_Office { get; set; }
        public string Reporting_Firm_Country_Code_of_Branch { get; set; }
        public string Reporting_Firm_Corporate_Sector { get; set; }
        public string Reporting_Firm_Financial_Status { get; set; }
        public string Broker_ID { get; set; }
        public string Broker_ID_Type { get; set; }
        public string Submitting_Entity_ID { get; set; }
        public string Submitting_Entity_ID_Type { get; set; }
        public string Clearing_Member_ID { get; set; }
        public string Clearing_Member_ID_Type { get; set; }
        public string Beneficiary_ID { get; set; }
        public string Beneficiary_ID_Type { get; set; }
        public string Trading_Capacity { get; set; }
        public string Buy___Sell_Indicator { get; set; }
        public string Counterparty_EEA_Status { get; set; }
        public string Commercial___Treasury_Activity { get; set; }
        public string Above_Clearing_Threshold { get; set; }
        public string Mark_to_Market_Value { get; set; }
        public string Mark_to_Market_Currency { get; set; }
        public Nullable<System.DateTime> Valuation_Date { get; set; }
        public Nullable<System.TimeSpan> Valuation_Time { get; set; }
        public string Valuation_Type { get; set; }
        public string Collateral_Type { get; set; }
        public string Collateral_Portfolio { get; set; }
        public string Collateral_Portfolio_Code { get; set; }
        public string Collateral_Value { get; set; }
        public string Collateral_Value_Currency { get; set; }
        public string Fund_Manager_ID { get; set; }
        public string Fund_Manager_ID_Type { get; set; }
        public string Instrument_ID_Taxonomy { get; set; }
        public string Instrument_ID { get; set; }
        public string ETD_Asset_Class_Type { get; set; }
        public string Instrument_Classification { get; set; }
        public string Underlying_Instrument_ID { get; set; }
        public string Underlying_Instrument_ID_Type { get; set; }
        public string Notional_Currency_1 { get; set; }
        public string Notional_Currency_2 { get; set; }
        public string Deliverable_Currency { get; set; }
        public string UTI { get; set; }
        public string MiFID_Transaction_Reference_Number { get; set; }
        public string Venue_ID { get; set; }
        public string Compression_Exercise { get; set; }
        public string Price___Rate { get; set; }
        public string Price_Notation { get; set; }
        public string Notional { get; set; }
        public string Price_Multiplier { get; set; }
        public string Quantity { get; set; }
        public string Up_Front_Payment { get; set; }
        public string Upfront_Payment_Currency { get; set; }
        public string Delivery_Type { get; set; }
        public Nullable<System.DateTime> Execution_Timestamp { get; set; }
        public Nullable<System.DateTime> Effective_Date { get; set; }
        public Nullable<System.DateTime> Maturity_Date { get; set; }
        public Nullable<System.DateTime> Termination_Date { get; set; }
        public Nullable<System.DateTime> Settlement_Date { get; set; }
        public string Master_Agreement { get; set; }
        public string Master_Agreement_Version { get; set; }
        public Nullable<System.DateTime> Confirmation_Timestamp { get; set; }
        public string Confirmation_Type { get; set; }
        public string Clearing_Obligation { get; set; }
        public string Cleared { get; set; }
        public Nullable<System.DateTime> Clearing_Timestamp { get; set; }
        public string CCP_ID { get; set; }
        public string CCP_ID_Type { get; set; }
        public string Intragroup { get; set; }
        public string Fixed_Rate_Leg_1 { get; set; }
        public string Fixed_Rate_Leg_2 { get; set; }
        public string Fixed_Rate_Day_Count { get; set; }
        public string Fixed_Leg_Payment_Frequency { get; set; }
        public string Floating_Rate_Payment_Frequency { get; set; }
        public string Floating_Rate_Reset_Frequency { get; set; }
        public string Floating_Rate_Leg_1 { get; set; }
        public string Floating_Rate_Leg_2 { get; set; }
        public string Currency_2 { get; set; }
        public string Exchange_Rate_1 { get; set; }
        public string Forward_Exchange_Rate { get; set; }
        public string Exchange_Rate_Basis { get; set; }
        public string Commodity_Base { get; set; }
        public string Commodity_Details { get; set; }
        public string Delivery_Point { get; set; }
        public string Interconnection_Point { get; set; }
        public string Load_Type { get; set; }
        public Nullable<System.DateTime> Delivery_Start_Timestamp { get; set; }
        public Nullable<System.DateTime> Delivery_End_Timestamp { get; set; }
        public string Contract_Capacity { get; set; }
        public string Quantity_Unit { get; set; }
        public string Price_Per_Time_Interval_Quantities { get; set; }
        public string Put___Call { get; set; }
        public string Option_Exercise_Type { get; set; }
        public string Strike_Price { get; set; }
        public string Action_Type { get; set; }
        public string Action_Type_Details { get; set; }
        public string Message_Type { get; set; }
        public string Notional_2 { get; set; }
        public string PUTI { get; set; }
        public string Instrument_Description { get; set; }
        public string Internal_ID { get; set; }
        public Nullable<System.DateTime> Event_Timestamp { get; set; }
        public Nullable<System.DateTime> Reporting_TimeStamp { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string cp { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
