//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emir_Mapping
    {
        public string Brocker { get; set; }
        public string InstrumentType { get; set; }
        public string CpSymbol { get; set; }
        public string VenueId { get; set; }
        public string InstrumentIDTaxonomy { get; set; }
        public string InstrumentID { get; set; }
        public string InstrumentClassification { get; set; }
        public string NotionalCurrency1 { get; set; }
        public string DeliverableCurrency { get; set; }
        public string PriceNotation { get; set; }
        public Nullable<double> PriceMultiplier { get; set; }
        public string DeliveryType { get; set; }
        public string ConfirmationType { get; set; }
        public string ClearingObligation { get; set; }
        public string Cleared { get; set; }
        public string CommodityBase { get; set; }
        public string CommodityDetails { get; set; }
        public long fullid { get; set; }
        public string filetype { get; set; }
        public int cLineStart { get; set; }
        public string Delimeter { get; set; }
        public string cp { get; set; }
        public int cBuySell { get; set; }
        public string BOSymbol { get; set; }
        public string UnderlyingInstrumentID { get; set; }
        public string UnderlyingInstrumentIDType { get; set; }
        public string FloatingRatePaymentFrequency { get; set; }
        public string FloatingRateResetFrequency { get; set; }
        public string FloatingRateLeg2 { get; set; }
        public string Currency2 { get; set; }
        public Nullable<double> ForwardExchangeRate { get; set; }
        public string ExchangeRateBasis { get; set; }
        public string PutCall { get; set; }
        public string OptionExerciseType { get; set; }
        public Nullable<double> StrikePrice { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public Nullable<System.DateTime> CPValueDate { get; set; }
    }
}
