//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FT
    {
        public long fullid { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string cp { get; set; }
        public string account_id { get; set; }
        public string symbol { get; set; }
        public string ccy { get; set; }
        public Nullable<double> value { get; set; }
        public string brocker { get; set; }
        public string Type { get; set; }
        public string Comment { get; set; }
        public Nullable<long> Reference { get; set; }
        public string User { get; set; }
        public Nullable<int> valid { get; set; }
        public System.DateTime timestamp { get; set; }
        public string BOSymbol { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<System.DateTime> TradeDate { get; set; }
        public string GrossPositionIndicator { get; set; }
        public string JOURNALACCOUNTCODE { get; set; }
        public Nullable<double> ValueCCY { get; set; }
        public string counterccy { get; set; }
        public Nullable<System.DateTime> Posted { get; set; }
        public string orderId { get; set; }
    }
}
