//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ftbo
    {
        public long id { get; set; }
        public string accountId { get; set; }
        public Nullable<System.DateTime> botimestamp { get; set; }
        public string operationType { get; set; }
        public string asset { get; set; }
        public Nullable<double> sum { get; set; }
        public string who { get; set; }
        public string gatewayId { get; set; }
        public Nullable<long> tradeNumber { get; set; }
        public string comment { get; set; }
        public string symbolId { get; set; }
        public Nullable<System.DateTime> valueDate { get; set; }
        public string orderId { get; set; }
        public Nullable<long> orderPos { get; set; }
        public Nullable<double> price { get; set; }
        public string clientType { get; set; }
        public string executionCounterparty { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string user { get; set; }
        public string category { get; set; }
        public string type { get; set; }
        public string internalComment { get; set; }
        public string symbolType { get; set; }
        public string baseCurrency { get; set; }
        public string settlementCurrency { get; set; }
        public Nullable<double> settlementCurrencyMovement { get; set; }
        public Nullable<double> exchangeCommission { get; set; }
        public string settlementCounterparty { get; set; }
        public string transferId { get; set; }
        public string clientCounterparty { get; set; }
        public string exanteCounterparty { get; set; }
    }
}
