//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class InitialTrade
    {
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<System.DateTime> TradeDate { get; set; }
        public string BrokerId { get; set; }
        public string Symbol { get; set; }
        public string Type { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<int> cp_id { get; set; }
        public Nullable<double> ExchangeFees { get; set; }
        public Nullable<double> Fee { get; set; }
        public Nullable<double> value { get; set; }
        public System.DateTime Timestamp { get; set; }
        public long FullId { get; set; }
        public string exchangeOrderId { get; set; }
        public string TypeOfTrade { get; set; }
        public string Comment { get; set; }
        public string ExchFeeCcy { get; set; }
        public string ClearingFeeCcy { get; set; }
        public string ccy { get; set; }
        public Nullable<double> Strike { get; set; }
        public string OptionType { get; set; }
        public Nullable<double> Fee2 { get; set; }
        public Nullable<double> Fee3 { get; set; }
    }
}
