//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mapping
    {
        public long fullid { get; set; }
        public string BrockerSymbol { get; set; }
        public string BOSymbol { get; set; }
        public string Brocker { get; set; }
        public Nullable<double> MtyPrice { get; set; }
        public Nullable<double> MtyVolume { get; set; }
        public string Type { get; set; }
        public Nullable<int> Round { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<long> valid { get; set; }
        public string username { get; set; }
        public Nullable<double> MtyStrike { get; set; }
        public Nullable<bool> UseDayInTicker { get; set; }
        public Nullable<sbyte> calendar { get; set; }
    }
}
