//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class md_swaps_googlespsh
    {
        public string account { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Pair { get; set; }
        public Nullable<double> FaceValue { get; set; }
        public Nullable<System.DateTime> NearLeg { get; set; }
        public Nullable<System.DateTime> FarLeg { get; set; }
        public Nullable<double> OpenPrice { get; set; }
        public Nullable<double> MarketPrice { get; set; }
        public Nullable<double> NearLegSpotPrice { get; set; }
        public Nullable<double> CurrentSpotPrice { get; set; }
        public Nullable<double> PnLNearLeg { get; set; }
        public Nullable<double> TradePnL { get; set; }
        public Nullable<double> C1Payable { get; set; }
        public string ccy { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<int> valid { get; set; }
        public string username { get; set; }
        public long fullid { get; set; }
    }
}
