//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenPaperTrade
    {
        public Nullable<System.DateTime> TradeDate { get; set; }
        public string User { get; set; }
        public string Account { get; set; }
        public string Confimation { get; set; }
        public string Counterparty { get; set; }
        public string Base { get; set; }
        public string Variable { get; set; }
        public Nullable<double> NearVolume { get; set; }
        public Nullable<double> NearPrice { get; set; }
        public Nullable<System.DateTime> NearDate { get; set; }
        public Nullable<double> NearValue { get; set; }
        public Nullable<double> FarVolume { get; set; }
        public Nullable<double> FarPrice { get; set; }
        public Nullable<System.DateTime> FarDate { get; set; }
        public Nullable<double> FarValue { get; set; }
        public string DealtCurrency { get; set; }
        public Nullable<double> NearClientPrice { get; set; }
        public Nullable<double> FarClientPrice { get; set; }
        public Nullable<double> NearClientVolume { get; set; }
        public Nullable<double> FarClientVolume { get; set; }
        public Nullable<double> NearClientValue { get; set; }
        public Nullable<double> FarClientValue { get; set; }
        public Nullable<double> Markup { get; set; }
        public string MarkupCurrency { get; set; }
        public Nullable<double> ExanteCost { get; set; }
        public Nullable<double> CostPer1M { get; set; }
        public Nullable<double> Fees { get; set; }
        public string TradeType { get; set; }
        public string BOUser { get; set; }
        public Nullable<System.DateTime> DateInputBO { get; set; }
        public string BOTradeIdNearLeg { get; set; }
        public string BOTradeIdFarLeg { get; set; }
        public string Comments { get; set; }
        public string Reconciled { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<int> valid { get; set; }
        public string username { get; set; }
        public long fullid { get; set; }
    }
}
