//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class QtyByAccounts
    {
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string Account_id { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<System.DateTime> ExDate { get; set; }
        public Nullable<System.DateTime> LastTradeDate { get; set; }
        public string Symbol { get; set; }
        public string isin { get; set; }
        public long id { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string Cp { get; set; }
    }
}
