//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reconcilation
    {
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<short> valid { get; set; }
        public string username { get; set; }
        public long id { get; set; }
        public Nullable<long> CpFull_id { get; set; }
        public Nullable<long> BOTradenumber { get; set; }
    }
}
