//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RowBalance
    {
        public string cp { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string Type { get; set; }
        public string ccy { get; set; }
        public Nullable<double> Value { get; set; }
        public string Comment { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Exchange { get; set; }
        public long fullid { get; set; }
        public string account { get; set; }
    }
}
