//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_
    {
        public string F1 { get; set; }
        public string symbolId { get; set; }
        public Nullable<double> leverageRate { get; set; }
        public string isin { get; set; }
        public Nullable<double> feedMpi { get; set; }
        public string exchangeName { get; set; }
        public string description { get; set; }
        public string currency { get; set; }
        public Nullable<double> contractMultiplier { get; set; }
    }
}
