//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model3Container : DbContext
    {
        public Model3Container()
            : base("name=Model3Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Contract> Contracts { get; set; }
        public DbSet<CpTrade> CpTrades { get; set; }
        public DbSet<Ctrade> Ctrades { get; set; }
        public DbSet<DailyCheck> DailyChecks { get; set; }
        public DbSet<PenPaperTrade> PenPaperTrades { get; set; }
        public DbSet<Price> Prices { get; set; }
    }
}
